name: BuildToDevServer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: "ubuntu-18.04"

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: SSH Remote Commands & deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: 22
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cd /project/FindingAssesmentApi
          git pull
          npm install
          npm run build
          pm2 restart assesment
          git stash
